### ISSUE TITLE
"com.squareup.wire.GrpcTest > cancelDuplexAfterRequestCompletes" is flaky

### ISSUE THREAD

**Issue by Egorand** [square/wire#1090]
Failed in this build: https://travis-ci.org/square/wire/builds/561048642

```
com.squareup.wire.GrpcTest > cancelDuplexAfterRequestCompletes FAILED
    java.lang.AssertionError: script had stuff left over: []
        at com.squareup.wire.MockRouteGuideService.awaitSuccess(MockRouteGuideService.kt:65)
        at com.squareup.wire.MockRouteGuideService$awaitSuccess$1.invokeSuspend(MockRouteGuideService.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.ResumeModeKt.resumeUninterceptedWithExceptionMode(ResumeMode.kt:56)
        at kotlinx.coroutines.TimeoutCoroutine.afterCompletionInternal(Timeout.kt:100)
        at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:309)
        at kotlinx.coroutines.JobSupport.tryFinalizeFinishingState(JobSupport.kt:235)
        at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:821)
        at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:764)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:111)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:324)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.kt:116)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:80)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at com.squareup.wire.GrpcTest.cancelDuplexAfterRequestCompletes(GrpcTest.kt:281)
```

**Comment by Egorand** [comment]
@swankjesse @oldergod has this been fixed?

**Comment by swankjesse** [comment]
Fixed.
