### ISSUE TITLE
Wire runtime issue with instant execution at execution time

### ISSUE THREAD

**Issue by stephanenicolas** [square/wire#1515]
After solving: #1496, there was another bug preventing me from testing the full build:

This bug is solved on the nightly version of gradle:https://issuetracker.google.com/issues/148400854

Using both the snapshot with the previous fix and the gradle nightly:`6.4-20200421230107+0000` and `AGP 4.0 beta 04`, I got a new stacktrace at execution time for instant execution:

```
(note to self: `failing a proto generation task`...)
Caused by: java.lang.NullPointerException
        at com.squareup.wire.gradle.WireInput.toLocations(WireInput.kt:127)
        at com.squareup.wire.gradle.WireTask.generateWireFiles(WireTask.kt:101)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
```

I will try to address the issue soon.

**Comment by Egorand** [comment]
Nice, thanks!

**Comment by stephanenicolas** [comment]
I can repro using 
* AGP:4.1.0-alpha09
* Kotlin:1.3.72
* Gradle:6.5-20200519143217+0000
```
6 instant execution problems were found, 3 of which seem unique.
- field 'configuration' from type 'com.squareup.wire.gradle.WireInput': cannot deserialize object of type 'org.gradle.api.artifacts.Configuration' as these are not supported with instant execution.
  See https://docs.gradle.org/6.5-20200519143217+0000/userguide/configuration_cache.html#disallowed_types
- field 'configuration' from type 'com.squareup.wire.gradle.WireInput': value 'file collection' is not assignable to 'org.gradle.api.artifacts.Configuration'
- field 'project' from type 'com.squareup.wire.gradle.WireInput': cannot deserialize object of type 'org.gradle.api.Project' as these are not supported with instant execution.
  See https://docs.gradle.org/6.5-20200519143217+0000/userguide/configuration_cache.html#disallowed_types
```

**Comment by oldergod** [comment]
Is it fixed then @stephanenicolas ?

**Comment by stephanenicolas** [comment]
Yes. Sorry, I forgot to close it.
