### ISSUE TITLE
How to use google/protobuf/any.proto

### ISSUE THREAD

**Issue by onexuan** [square/wire#1562]
I want to use google.protobuf.Any, How to create it 

syntax = "proto3";

import "google/protobuf/any.proto";

message Result {

  int32 code = 1;
  int64 version = 2;
  google.protobuf.Any data = 3;
}

Task :app:generateWireFile FAILED
Exception in thread "main" java.io.FileNotFoundException: Failed to locate google/protobuf/any.proto in [src/main/proto]
	at com.squareup.wire.schema.SchemaLoader.loadFromDirectories(SchemaLoader.java:155)
	at com.squareup.wire.schema.SchemaLoader.load(SchemaLoader.java:106)
	at com.squareup.wire.WireCompiler.compile(WireCompiler.java:211)
	at com.squareup.wire.WireCompiler.main(WireCompiler.java:126)

**Comment by onexuan** [comment]
I have fix
