### ISSUE TITLE
RealGrpcCall/GrpcClient configurability for grpc-accept-encoding and grpc-encoding

### ISSUE THREAD

**Issue by buildbreaker** [square/wire#1777]
Hello, I am currently using wire to talk to a back end grpc service which does not support any compression for requests/responses.

I did some spelunking to figure out if I can configure or work around this issue but it looks like the [`RealGrpcCall`](https://github.com/square/wire/blob/master/wire-library/wire-grpc-client/src/jvmMain/kotlin/com/squareup/wire/internal/grpc.kt#L51) set the request encoding to be `gzip` always. Additionally, the [`GrpcClient`](https://github.com/square/wire/blob/master/wire-library/wire-grpc-client/src/jvmMain/kotlin/com/squareup/wire/GrpcClient.kt#L69-L70) also sets the headers `grpc-accept-encoding` and `grpc-encoding` to be `gzip` as well.

Are there immediate plans (or even ideas) on making this configurable?

I'm also happy to propose change (and help) for this but from a glance at the code, it seems like a little intrusive and non-trivial of a change (I still am happy to collaborate!)

Thank you,
Alan

**Comment by swankjesse** [comment]
Yeah, good idea. It’s annoying that it isn’t negotiable!

I think we probably configure this in the same way as OkHttp’s WebSocket compression.
https://square.github.io/okhttp/4.x/okhttp/okhttp3/-ok-http-client/-builder/min-web-socket-message-to-compress/

We’d do Long.MAX_VALUE for no compression ever.

**Comment by buildbreaker** [comment]
Thanks for the quick response, @swankjesse!

I'll give that a shot and come back with the results!

**Comment by buildbreaker** [comment]
Actually, this is a bit of a bummer but your suggestion of `Long.MAX_VALUE` will still flip the encryption bit to `1` ☹️ 

In the message preamble within the [`GrpcMessageSink`](https://github.com/square/wire/blob/master/wire-library/wire-grpc-client/src/commonMain/kotlin/com/squareup/wire/internal/GrpcMessageSink.kt#L35): since `grpcEncoding` is always `gzip` in the [grpc.kt](https://github.com/square/wire/blob/master/wire-library/wire-grpc-client/src/jvmMain/kotlin/com/squareup/wire/internal/grpc.kt#L51)

**Comment by swankjesse** [comment]
I was intending to suggest we use MAX_VALUE as a special value that'd never flip that bit.

**Comment by kam1sh** [comment]
I'm also very interested in solving of that issue: I work with the CRI-O daemon that has no support of gzip, so when I'm trying to communicate with its gRPC API, I get following error:
```
Exception in thread "main" java.io.IOException: grpc failed status=200, grpc-status=12, grpc-message=grpc: Decompressor is not installed for grpc-encoding "gzip"
        at com.squareup.wire.internal.GrpcKt.grpcResponseToException(grpc.kt:164)
        at com.squareup.wire.internal.RealGrpcCall.readExactlyOneAndClose(RealGrpcCall.kt:104)
        at com.squareup.wire.internal.RealGrpcCall.access$readExactlyOneAndClose(RealGrpcCall.kt:32)
        at com.squareup.wire.internal.RealGrpcCall$execute$$inlined$suspendCancellableCoroutine$lambda$2.onResponse(RealGrpcCall.kt:64)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.net.ProtocolException: expected 1 message but got none
        at com.squareup.wire.internal.GrpcMessageSource.readExactlyOneAndClose(GrpcMessageSource.kt:65)
        at com.squareup.wire.internal.RealGrpcCall.readExactlyOneAndClose(RealGrpcCall.kt:102)
        ... 6 more
```

I'll be very happy and thankful if you could find the way to disable gzip =) maybe I can also help with providing PR, if you need...

**Comment by erawhctim** [comment]
> I was intending to suggest we use MAX_VALUE as a special value that'd never flip that bit.

Is this behavior you're planning to add, or was this more of a suggestion/discussion? Not sure if that change would land in OkHttp or Wire.
Based on the errors I'm seeing, this sounds like a feature I could benefit from.


We're experimenting with GRPC and using Wire in our clients, and I'm running into an issue related to gzip since our GRPC server isn't configured to use it: 
```
Decompressor is not installed for grpc-encoding "gzip"
```

If I intercept the request and remove the `grpc-encoding` and `grpc-accept-encoding` headers, I get a different error (and unfortunately that's about where my knowledge of GRPC ends 🙂):
```
compressed flag set with identity or empty encoding
```

Sounds like the same issue @buildbreaker raised initially. I'd be happy to help with a PR for this, if you wouldn't mind pointing me in the direction of where to start?

**Comment by k0shk0sh** [comment]
getting the same logs as above 

```
2021-04-23 13:48:57.548 com.lovoo.android.grpc W/System.err: java.io.IOException: gRPC transport failure (HTTP status=200, grpc-status=null, grpc-message=null)
2021-04-23 13:48:57.548 com.lovoo.android.grpc W/System.err:     at com.squareup.wire.internal.GrpcKt.grpcResponseToException(grpc.kt:166)
2021-04-23 13:48:57.548 com.lovoo.android.grpc W/System.err:     at com.squareup.wire.internal.RealGrpcCall.readExactlyOneAndClose(RealGrpcCall.kt:104)
2021-04-23 13:48:57.548 com.lovoo.android.grpc W/System.err:     at com.squareup.wire.internal.RealGrpcCall.access$readExactlyOneAndClose(RealGrpcCall.kt:32)
2021-04-23 13:48:57.548 com.lovoo.android.grpc W/System.err:     at com.squareup.wire.internal.RealGrpcCall$enqueue$1.onResponse(RealGrpcCall.kt:89)
2021-04-23 13:48:57.548 com.lovoo.android.grpc W/System.err:     at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:504)
2021-04-23 13:48:57.548 com.lovoo.android.grpc W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2021-04-23 13:48:57.548 com.lovoo.android.grpc W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2021-04-23 13:48:57.548 com.lovoo.android.grpc W/System.err:     at java.lang.Thread.run(Thread.java:923)
```

its related to our go-server after enabling gzip that the response is not compressed properly and its not returned, our backend engineer narrow it down to Cloudflare and currently still looking for a fix. 

It would be nice to remove the compression at all as if we look into the gRPC-Java for example, it doesn't do it neither send the encoding.
