### ISSUE TITLE
Kotlin compilation fails: Method too large

### ISSUE THREAD

**Issue by kronstein** [square/wire#1831]
Is it dupe of #1575? It's closed, but compilation fails on large protos on com.squareup.wire:wire-gradle-plugin:3.4.0:

Consider we have something like this:
```
syntax = "proto3";

// import other messages here

message MyLargeWrapper {
   // some fields
  oneof message {
     // Nearly 300 messages to choose from.
  }
}
```

Compilation failed:
```
Caused by: org.jetbrains.org.objectweb.asm.MethodTooLargeException: Method too large: com/company/app/MyLargeWrapper$Companion$ADAPTER$1.redact (Lcom/company/app/MyLargeWrapper;)Lcom/company/app/MyLargeWrapper;
	at org.jetbrains.org.objectweb.asm.MethodWriter.computeMethodInfoSize(MethodWriter.java:2089)
	at org.jetbrains.org.objectweb.asm.ClassWriter.toByteArray(ClassWriter.java:458)
	at org.jetbrains.kotlin.codegen.ClassBuilderFactories$2.asBytes(ClassBuilderFactories.java:118)
	at org.jetbrains.kotlin.codegen.DelegatingClassBuilderFactory.asBytes(DelegatingClassBuilderFactory.kt:36)
	at org.jetbrains.kotlin.codegen.DelegatingClassBuilderFactory.asBytes(DelegatingClassBuilderFactory.kt:36)
	at org.jetbrains.kotlin.codegen.DelegatingClassBuilderFactory.asBytes(DelegatingClassBuilderFactory.kt:36)
	at org.jetbrains.kotlin.android.synthetic.codegen.ParcelableClinitClassBuilderInterceptorExtension$ParcelableClinitClassBuilderFactory.asBytes(ParcelableClinitClassBuilderInterceptorExtension.kt:58)
	at org.jetbrains.kotlin.android.synthetic.codegen.AbstractAndroidOnDestroyClassBuilderInterceptorExtension$AndroidOnDestroyClassBuilderFactory.asBytes(AndroidOnDestroyClassBuilderInterceptorExtension.kt:63)
	at org.jetbrains.kotlin.codegen.ClassFileFactory$ClassBuilderAndSourceFileList.asBytes(ClassFileFactory.java:348)
	at org.jetbrains.kotlin.codegen.ClassFileFactory$OutputClassFile.asByteArray(ClassFileFactory.java:313)
	... 45 more


> Task :app:compileDebugKotlin FAILED
e: java.lang.IllegalStateException: Backend Internal error: Exception during file facade code generation
```

**Comment by kronstein** [comment]
Duplicate of #1448
