### ISSUE TITLE
Wire plugin doesn't work in a Java only project

### ISSUE THREAD

**Issue by amun120** [square/wire#1864]
Hi there, I'm seeing this error when importing the gradle plugin:

```
Caused by: java.lang.IllegalStateException: Couldn't find debug in {androidTest=null, androidTestDebug=null, debug=null, main=null, release=null, test=null, testDebug=null, testRelease=null}
	at com.squareup.wire.gradle.kotlin.SourceRootsKt.sourceRoots(SourceRoots.kt:148)
	at com.squareup.wire.gradle.kotlin.SourceRootsKt.sourceRoots(SourceRoots.kt:73)
	at com.squareup.wire.gradle.WirePlugin$sources$2.invoke(WirePlugin.kt:39)
	at com.squareup.wire.gradle.WirePlugin$sources$2.invoke(WirePlugin.kt:31)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at com.squareup.wire.gradle.WirePlugin.getSources(WirePlugin.kt)
	at com.squareup.wire.gradle.WirePlugin.setupWireTasks(WirePlugin.kt:122)
	at com.squareup.wire.gradle.WirePlugin.access$setupWireTasks(WirePlugin.kt:31)
	at com.squareup.wire.gradle.WirePlugin$apply$androidPluginHandler$1$1.execute(WirePlugin.kt:57)
...
```

**build.gradle**:
```
apply plugin: 'com.squareup.wire'

wire {
    java {}
}

...


buildscript {
    repositories {
        mavenCentral()
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.6.3'
        classpath 'com.squareup.wire:wire-gradle-plugin:3.5.0'
    }
}
```

Android Gradle Plugin Version: **3.6.3**
Gradle Version: **5.6.4**

**Comment by oldergod** [comment]
The Wire plugin doesn't work in a Java only project. We need to fix that.

**Comment by yogeshmoradiya121** [comment]
same error shows java android project

**Comment by oldergod** [comment]
The fix hasn't been released yet.
It's in the `3.6.1-SNAPSHOT` if you wanna try it.
