### ISSUE TITLE
Crash in ProtoAdapter.apply

### ISSUE THREAD

**Issue by sushilr** [square/wire#1873]
We've been trying to address a crasher in our app that seems to be originating in one of our Rx chains and RxDogTag points to a line in the ProtoAdapter - specifically `ProtoAdapter.kt:1com.squareup.wire.ProtoAdapterKt.apply`. Here is the full stacktrace: 

```
io.reactivex.rxjava3.exceptions.OnErrorNotImplementedException: java.net.SocketTimeoutException: timeout
        at unknown method(unknown file)

Caused by: slack.api.exceptions.ApiCallException: java.net.SocketTimeoutException: timeout
        at com.squareup.wire.ProtoAdapterKt.apply(ProtoAdapter.kt:1)
        at [[ ↑↑ Inferred subscribe point ↑↑ ]].(unknown)
        at [[ ↓↓ Original trace ↓↓ ]].(unknown)
        at slack.api.ApiRxAdapter$SingleEmitterCallback.onFailure(ApiRxAdapter.kt:1)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:24)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
```

Only one of our components (telemetry) uses Wire, and I'm not sure why we've started to see crashes all of a sudden in our latest release version. 

We also  aren't able to tell how Wire is getting triggered from our stacktraces and it doesn't seem to be happening from one call site either. The only evidence we have is the RxDogTag pointing to the `ProtoAdapter`. 

The only change of interest that went into this version is an upgrade to Wire from `3.4.0` to `3.5.0`. Have there been any such reports from other folks after upgrading to this version? 

Under what circumstances do things break in the ProtoAdapter? Failed encoding/decoding? Any suggestions of where we could look to help diagnose? Thank you!

**Comment by JakeWharton** [comment]
The exception is a timeout from OkHttp which can happen anywhere and must always be handled. Wire is just trying to read from the network socket and the network has disappeared. You must always assume the network layer can fail with an IOException subtype, but based on the exception being wrapped in `OnErrorNotImplementedException` you are not handling any errors currently.
