### ISSUE TITLE
wire-runtime crashes when re-serializing unknown repeated fields.

### ISSUE THREAD

**Issue by asarazan** [square/wire#195]
See https://github.com/asarazan/WireBugReduced for a reduced test case.

TL;DR
1. Send an object with a repeated field to a client that doesn't know about that field
2. Have the client parse, then call toByteArray() on that object
3. Crash:

```
Caused by: java.io.IOException: Out of space: position=7, limit=7
at com.squareup.wire.WireOutput.writeRawBytes(WireOutput.java:244)
at com.squareup.wire.WireOutput.writeRawBytes(WireOutput.java:233)
at com.squareup.wire.UnknownFieldMap$LengthDelimitedFieldValue.write(UnknownFieldMap.java:170)
at com.squareup.wire.UnknownFieldMap.write(UnknownFieldMap.java:260)
at com.squareup.wire.Message.writeUnknownFieldMap(Message.java:238)
at com.squareup.wire.MessageAdapter.write(MessageAdapter.java:310)
at com.squareup.wire.MessageAdapter.writeMessage(MessageAdapter.java:504)
at com.squareup.wire.MessageAdapter.writeValueNoTag(MessageAdapter.java:491)
at com.squareup.wire.MessageAdapter.writeValue(MessageAdapter.java:465)
at com.squareup.wire.MessageAdapter.write(MessageAdapter.java:300)
at com.squareup.wire.MessageAdapter.toByteArray(MessageAdapter.java:359)
```

**Comment by asarazan** [comment]
The issue appears to stem from `LengthDelimitedFieldValue` at lines 164 and 168:

```
    @Override public int getSerializedSize() {
      return WireOutput.varint32Size(value.size()) + value.size();
    }

    @Override public void write(int tag, WireOutput output) throws IOException {
      output.writeTag(tag, WireType.LENGTH_DELIMITED);
      output.writeVarint32(value.size());
      output.writeRawBytes(value.toByteArray());
    }
```

`getSerializedSize` doesn't take the tag length into account, whereas `write` does, leading to not enough space being allocated.

**Comment by JakeWharton** [comment]
Nice find. Feel free to send a PR with a test if you have time. Otherwise we'll get to this soon!

**Comment by asarazan** [comment]
PR sent.
