### ISSUE TITLE
Unable to run android application in "wire-grpc-sample"

### ISSUE THREAD

**Issue by dimsuz** [square/wire#2037]
Steps to reproduce

1. Clone the `wire` project from github to some clean directory
2. Run `:samples:wire-grpc-sample:client:installDebug` task
3. Run an app on the emulator (I used Pixel 2 API 29 one)
4. Observe this crash

```
E  Process: com.squareup.wire.whiteboard, PID: 6683
E  java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.squareup.wire.whiteboard/com.squareup.wire.whiteboard.MainActivity}: java.lang.ClassNotFoundException: Did
   n't find class "com.squareup.wire.whiteboard.MainActivity" on path: DexPathList[[zip file "/data/app/com.squareup.wire.whiteboard-M29FMHxlYjpvs2NiV32i7w==/base.apk"],nativeLibraryDire
   ctories=[/data/app/com.squareup.wire.whiteboard-M29FMHxlYjpvs2NiV32i7w==/lib/x86, /system/lib, /system/product/lib]]
E      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3194)
E      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
E      at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
E      at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E      at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
E      at android.os.Handler.dispatchMessage(Handler.java:107)
E      at android.os.Looper.loop(Looper.java:214)
E      at android.app.ActivityThread.main(ActivityThread.java:7356)
E      at java.lang.reflect.Method.invoke(Native Method)
E      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E  Caused by: java.lang.ClassNotFoundException: Didn't find class "com.squareup.wire.whiteboard.MainActivity" on path: DexPathList[[zip file "/data/app/com.squareup.wire.whiteboard-M29FM
   HxlYjpvs2NiV32i7w==/base.apk"],nativeLibraryDirectories=[/data/app/com.squareup.wire.whiteboard-M29FMHxlYjpvs2NiV32i7w==/lib/x86, /system/lib, /system/product/lib]]
E      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
E      at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E      at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E      at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
E      at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:43)
E      at android.app.Instrumentation.newActivity(Instrumentation.java:1243)
E      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3182)
E      ... 11 more
```

This is a very noobish situation, but I'm out of ideas why this happens.
* Tried adding `exported = true` to the activity in the manifest, didn't help.
* Checked if R8 is being run: don't see it in gradle output.
* Used "Analyze APK" and **I don't find** `MainActivity` in any of `classesN.dex` files, but what could strip it and why? (unless I somehow missed it)

**Comment by oldergod** [comment]
I reproduced and have no idea either why this would be happening. Hmm.

**Comment by dimsuz** [comment]
One thing that I also noticed: I've accidentally pasted some random stuff into sample's MainActivity and _it didn't break_ the compilation. So I thought that this means that MainActivity doesn't end up in the final apk because it isn't even being compiled.

Although I'd recheck that, because it was late in the evening...
Another thought was that this might have something to do with KMP gradle plugin, judging from the gradle output it is being used.

**Comment by oldergod** [comment]
I've rewritten it a bit in https://github.com/square/wire/pull/2289 and this should make it usable again.
