### ISSUE TITLE
Wire-compiler cannot parse hex enums

### ISSUE THREAD

**Issue by sureshjoshi** [square/wire#212]
Hey all, love the library. Have used it in a few past projects.

Ran into an issue today using a .proto file from a client. They use hex inside of the protobuffer enums

    enum Start {
      PACKAGE_START   = 0X0a;
    }

    enum End {
      PACKAGE_END      = 0X04;
    }

Here is the exception which get's thrown back:

    Exception in thread "main" java.lang.IllegalStateException: Syntax error in proto-repo/ACS.proto a 14:27: expected an integer but was 0X0a
	at com.squareup.protoparser.ProtoSchemaParser.unexpected(ProtoSchemaParser.java:743)
	at com.squareup.protoparser.ProtoSchemaParser.readInt(ProtoSchemaParser.java:638)
	at com.squareup.protoparser.ProtoSchemaParser.readDeclaration(ProtoSchemaParser.java:183)
	at com.squareup.protoparser.ProtoSchemaParser.readEnumType(ProtoSchemaParser.java:296)
	at com.squareup.protoparser.ProtoSchemaParser.readDeclaration(ProtoSchemaParser.java:165)
	at com.squareup.protoparser.ProtoSchemaParser.readProtoFile(ProtoSchemaParser.java:119)
	at com.squareup.protoparser.ProtoSchemaParser.parse(ProtoSchemaParser.java:37)
	at com.squareup.wire.IO$FileIO.parse(IO.java:42)
	at com.squareup.wire.WireCompiler.compile(WireCompiler.java:172)
	at com.squareup.wire.WireCompiler.main(WireCompiler.java:94)

My question. Is this a bug? Or acting as designed? The client is using nanopb to generate the files: https://github.com/nanopb/nanopb

I've never run into this problem before, but then again, I usually use integers in enums.

**Comment by danrice-square** [comment]
I've never seen anyone use an upper-case 'X' to denote hex. A lower-case 'x' should work fine.

**Comment by danrice-square** [comment]
See https://github.com/square/protoparser/pull/100/files.

**Comment by sureshjoshi** [comment]
Hey Dan, thanks! Yep, was the capital X...

In all fairness, I've been doing embedded dev for like 10 years and this is the first example of capitalized X's I've seen. But to each their own.
