### ISSUE TITLE
META-INF/INDEX.LIST:1:1: unexpected label: JarIndex-Version when including proto-google-common-protos using wire

### ISSUE THREAD

**Issue by chemouna** [square/wire#2120]
Hi, i'm importing `com.google.api.grpc:proto-google-common-protos:1.18.0` ([api-common-protos](https://github.com/googleapis/api-common-protos))  to get some common proto definitions but when i run `generateProtos` i'm getting the following error:

```
Syntax error in com.google.api.grpc/proto-google-common-protos/1.18.0/b69bc5942255dc9dd2d2de432c4b99a5b483679/proto-google-common-protos-1.18.0.jar/META-INF/INDEX.LIST:1:1: unexpected label: JarIndex-Version
```

this is the relevant wire setup i'm using:
```
sourcePath {
  srcJar = "com.google.api.grpc:proto-google-common-protos:1.18.0"
  exclude("google/type/**") // this is intentionally excluded because these proto files are available through another dependency
}
```
i checked the jar and INDEX.LIST file contains:
```
JarIndex-Version: 1.0

proto-google-common-protos-1.18.0.jar
META-INF
META-INF/maven
META-INF/maven/com.google.api.grpc
META-INF/maven/com.google.api.grpc/proto-google-common-protos
com
com/google
com/google/api
com/google/cloud
com/google/cloud/audit
com/google/geo
com/google/geo/type
com/google/logging
com/google/logging/type
com/google/longrunning
com/google/rpc
com/google/rpc/context
com/google/type
google
google/api
google/cloud
google/cloud/audit
google/geo
google/geo/type
google/logging
google/logging/type
google/longrunning
google/rpc
google/rpc/context
google/type
```

using protoPath works but i want to have proto types from proto-google-common-protos generated to be used outside of the module.

```
protoPath {
  srcJar = "com.google.api.grpc:proto-google-common-protos:1.18.0"
  exclude("google/type/**") // this is intentionally excluded because these proto files are available through another dependency
}
```

any pointers into why wire is throwing this error and how to get around it ?

thank you

**Comment by oldergod** [comment]
Wire should not read this file... I wonder why it does so.

**Comment by oldergod** [comment]
I am not able to repro. Would you be able to create small project which fails?

**Comment by Maragues** [comment]
@oldergod I'm having the exact same issue today. It only happens when I add an `exclude` clause

```kotlin
plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.androidLibrary)
    alias(libs.plugins.realm)
    alias(libs.plugins.wire)
}

wire {
    sourcePath {
        srcJar("com.google.api.grpc:proto-google-common-protos:2.39.0")
        exclude("com/google/longrunning/**") // problematic!
    }

    sourcePath {
        srcJar("com.google.protobuf:protobuf-java:3.21.9")
    }

    kotlin {
        exclusive = true
    }
}
```

If I remove the `exclude`, there`s an expected compilation error at `compileDebugKotlinAndroid` task

```
com/google/longrunning/GrpcOperationsClient.kt:7:26 Unresolved reference: GrpcCall
```

Because I don't care about grpc in this project, I want to exclude everything under `com/google/longrunning` path. Thus, I add the `exclude` clause, and `generateCommonMainProtos` task starts failing

```
Caused by: java.lang.IllegalStateException: Syntax error in /.gradle/caches/modules-2/files-2.1/com.google.api.grpc/proto-google-common-protos/2.39.0/.../proto-google-common-protos-2.20.0.jar/META-INF/INDEX.LIST:1:1: unexpected label: JarIndex-Version
        at com.squareup.wire.schema.internal.parser.SyntaxReader.unexpected(SyntaxReader.kt:424)
        at com.squareup.wire.schema.internal.parser.ProtoParser.readDeclaration(ProtoParser.kt:172)
        at com.squareup.wire.schema.internal.parser.ProtoParser.readProtoFile(ProtoParser.kt:69)
        at com.squareup.wire.schema.internal.parser.ProtoParser$Companion.parse(ProtoParser.kt:664)
        at com.squareup.wire.schema.RootsKt.parse(Roots.kt:66)
        at com.squareup.wire.schema.internal.CommonSchemaLoader.load(CommonSchemaLoader.kt:166)
        at com.squareup.wire.schema.internal.CommonSchemaLoader.loadSourcePathFiles$wire_schema(CommonSchemaLoader.kt:120)
        at com.squareup.wire.schema.internal.CommonSchemaLoader.loadSchema(CommonSchemaLoader.kt:103)
        at com.squareup.wire.schema.SchemaLoader.loadSchema(SchemaLoader.kt:77)
        at com.squareup.wire.schema.WireRun.execute$wire_schema(WireRun.kt:248)
        at com.squareup.wire.schema.WireRun.execute(WireRun.kt:234)
        at com.squareup.wire.gradle.WireTask.generateWireFiles(WireTask.kt:178)
```

Long at the gradle tasks, `generateCommonMainProtos` is executed before `compileDebugKotlinAndroid`

```
// using --dry-run
:shared:generateCommonMainProtos
:shared:compileDebugKotlinAndroid
```

Thus, this looks to me like a parsing bug? I have no clue of what that `JarIndex-Version` thing is for, but it's shipped in the proto .jar.

**Comment by oldergod** [comment]
@Maragues I believe our support of wildcards in include/exclude within `sourcePath/protoPath` blocks are broken. I've tried a while ago to fix it but I wasn't able to get it fixed.

**Comment by Maragues** [comment]
I tried to exclude without wildcards, using `exclude("com/google/longrunning/operations.proto")`. 

But, same `Syntax error`

Thanks for fast reply!

**Comment by oldergod** [comment]
Hmm a bit puzzling to me.

Otherwise for the `com/google/longrunning/GrpcOperationsClient.kt:7:26 Unresolved reference: GrpcCall` error, you need the dependency on `wire-grpc-client` as well.
