### ISSUE TITLE
Option allow_alias in enum causes exception

### ISSUE THREAD

**Issue by sureshjoshi** [square/wire#213]
enum foo {
      option allow_alias = true;
      bar1        = 16;
      bar2        = 20;	
      bar3       = 100;
      bar4       = 128;	
    }

This might be related to #49, which was batted around between here and square/protoparser. I got an exception, and when I remove 'option allow_alias = true', everything compiles fine. For me, the bigger question is why this enum even contains that string, however, the message files are (unfortunately) created by someone else and are out of my control.

allow_alias inside of an enum seems to be legit according to the protobuf docs: https://developers.google.com/protocol-buffers/docs/proto3

Also, nanopb compiles it (however, I think nanopb is actually really lax with the rules), because there is also a duplicate tag in my set of protobufs that nanopb apparently allows (which is bad).

    Exception in thread "main" java.lang.NullPointerException
	at com.squareup.wire.OptionsMapMaker.insertOptionHelper(OptionsMapMaker.java:202)
	at com.squareup.wire.OptionsMapMaker.insertOptionHelper(OptionsMapMaker.java:194)
	at com.squareup.wire.OptionsMapMaker.insertOption(OptionsMapMaker.java:177)
	at com.squareup.wire.OptionsMapMaker.createEnumOptionsMap(OptionsMapMaker.java:47)
	at com.squareup.wire.MessageWriter.emitType(MessageWriter.java:128)
	at com.squareup.wire.WireCompiler.emitMessageClass(WireCompiler.java:829)
	at com.squareup.wire.WireCompiler.compileOne(WireCompiler.java:352)
	at com.squareup.wire.WireCompiler.compile(WireCompiler.java:191)
	at com.squareup.wire.WireCompiler.main(WireCompiler.java:94)

I'm wondering if this should just return a "option not supported" string?

**Comment by sureshjoshi** [comment]
Actually, just ran into an instance where this is option is actually used by my client:

    enum System_Property_Length {
      option allow_alias = true;
      SYSTEM_SN_LENGTH       = 12;
      SYSTEM_FW_LENGTH       = 12;
      SYSTEM_HW_LENGTH       = 14;
    }

I have to also admit, I don't really like the alias now, because right here, I can't tell if that second 12 is a typo.

**Comment by fangzhzh** [comment]
almost same thing here.


``` java
// with allow_alias option
enum Status                                                                                                           
{                                                                                                                     
    option allow_alias = true;
   DELETE       = 0;
    NORMAL       = 1;
    REVIEWING    = 2;
    BANNED       = 3;
    INVALID      = 4;
    INVALID_HIDE = 5;

    CREATED = 0;
}

Exception in thread "main" java.lang.NullPointerException
	at com.squareup.wire.MessageWriter.emitEnumOptions(MessageWriter.java:297)
	at com.squareup.wire.MessageWriter.emitType(MessageWriter.java:130)
	at com.squareup.wire.WireCompiler.emitMessageClass(WireCompiler.java:835)
	at com.squareup.wire.WireCompiler.compileOne(WireCompiler.java:354)
	at com.squareup.wire.WireCompiler.compile(WireCompiler.java:195)
	at com.squareup.wire.WireCompiler.main(WireCompiler.java:98)
```
without option allow_alias = true;
``` java
// without allow_alias option
enum Status                                                                                                           
{                                                                                                                     
   DELETE       = 0;
    NORMAL       = 1;
    REVIEWING    = 2;
    BANNED       = 3;
    INVALID      = 4;
    INVALID_HIDE = 5;

    CREATED = 0;
}


Exception in thread "main" java.lang.IllegalStateException: Duplicate tag 0 in 
db.Status
	at com.squareup.protoparser.EnumElement.validateTagUniqueness(EnumElement.java:28)
	at com.squareup.protoparser.EnumElement.access$200(EnumElement.java:19)
	at com.squareup.protoparser.EnumElement$Builder.build(EnumElement.java:154)
	at com.squareup.protoparser.ProtoParser.readEnumElement(ProtoParser.java:314)
	at com.squareup.protoparser.ProtoParser.readDeclaration(ProtoParser.java:155)
	at com.squareup.protoparser.ProtoParser.readProtoFile(ProtoParser.java:92)
	at com.squareup.protoparser.ProtoParser.parse(ProtoParser.java:56)
	at com.squareup.wire.IO$FileIO.parse(IO.java:41)
	at com.squareup.wire.WireCompiler.loadSymbolsHelper(WireCompiler.java:621)
	at com.squareup.wire.WireCompiler.loadSymbols(WireCompiler.java:610)
	at com.squareup.wire.WireCompiler.compile(WireCompiler.java:178)
	at com.squareup.wire.WireCompiler.main(WireCompiler.java:98)
Exception in thread "main" java.lang.IllegalStateException: Duplicate tag 0 in PBData.beeshop.db.Status
	at com.squareup.protoparser.EnumElement.validateTagUniqueness(EnumElement.java:28)
	at com.squareup.protoparser.EnumElement.access$200(EnumElement.java:19)
	at com.squareup.protoparser.EnumElement$Builder.build(EnumElement.java:154)
	at com.squareup.protoparser.ProtoParser.readEnumElement(ProtoParser.java:314)
	at com.squareup.protoparser.ProtoParser.readDeclaration(ProtoParser.java:155)
	at com.squareup.protoparser.ProtoParser.readProtoFile(ProtoParser.java:92)
	at com.squareup.protoparser.ProtoParser.parse(ProtoParser.java:56)
	at com.squareup.wire.IO$FileIO.parse(IO.java:41)
	at com.squareup.wire.WireCompiler.compile(WireCompiler.java:176)
	at com.squareup.wire.WireCompiler.main(WireCompiler.java:98)

```

**Comment by swankjesse** [comment]
Fixed on master.
