### ISSUE TITLE
JSON serializers fail on fields declared after repeated fields in Kotlin types without Java interop

### ISSUE THREAD

**Issue by Egorand** [square/wire#2153]
To reproduce:

1. Add a new field to the `wire-library/wire-tests/src/commonTest/shared/proto/proto2/person_kotlin.proto` message:

```diff
  message Person {
    ...
    repeated PhoneNumber phone = 4;    
+
+   optional bool canadian = 5;
  }    
```

**Note**: the name of the new field should not start with "is", otherwise you'll hit #2152.

2. Regenerate test protos by running `./gradlew generateTests`.
3. Run the `wire-moshi-adapter/src/test/.../MoshiPersonTest.kotlinWithoutBuilderFromJson` test.
4. Test will fail with the following exception:

```
argument type mismatch
java.lang.IllegalArgumentException: argument type mismatch
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.squareup.wire.KotlinConstructorBuilder.build(KotlinConstructorBuilder.kt:70)
	at com.squareup.wire.MessageJsonAdapter.fromJson(MessageJsonAdapter.kt:84)
	at com.squareup.wire.MessageJsonAdapter.fromJson(MessageJsonAdapter.kt:24)
	at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
	at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:70)
	at com.squareup.wire.MoshiPersonTest.kotlinWithoutBuilderFromJson(MoshiPersonTest.kt:41)
```

The source of the problem seems to be the ordering of properties annotated with `WireField` in the generated code:

```kotlin
public class Person(
  @field:WireField(tag = 1)
  public val name: String,
  @field:WireField(tag = 2)
  public val id: Int,
  ...
  phone: List<PhoneNumber> = emptyList(),
  @field:WireField(tag = 5)
  public val canadian: Boolean? = null,
) : Message<..., ...> {
  @field:WireField(tag = 4)
  public val phone: List<PhoneNumber>
}
```

The following code inside `KotlinConstructorBuilder` retrieves all properties annotated with `WireField` in the order of declaration in the file, gets their values, locates the constructor and calls it passing the property values:

```kotlin
@Suppress("UNCHECKED_CAST")
override fun build(): M {
  val args = messageType.declaredWireFields() 
      .map(::get) 
      .plus(buildUnknownFields())
      .toTypedArray()

  val constructor = messageType.declaredConstructors.first()

  return constructor.newInstance(*args) as M
}

private fun Class<M>.declaredWireFields() = declaredFields
    .mapNotNull {
      it.declaredAnnotations.filterIsInstance(WireField::class.java).firstOrNull()
    }
```

But because the order in which `WireField` properties are declared differs from the order in which they appear in the constructor, arguments get passed in the wrong order leading to the type mismatch:

```
order of WireFields: (name, id, canadian, phone)
order of constructor params: (name, id, phone, canadian)
```

Working on a fix!

**Comment by Egorand** [comment]
Looks like this would be an issue for all types of proto fields for which the property with the `WireField` annotation will be generated inside the class body, as opposed to the default constructor. Need a test case that covers the following types of fields:

- `repeated`
- `map`
- `struct`
- `oneof`, both flat and boxed
