### ISSUE TITLE
GrpcStreamingCall should disable read and write timeouts

### ISSUE THREAD

**Issue by swankjesse** [square/wire#2174]
We’ve got a gRPC streaming call that’s failing with a read timeout like this:

```
java.net.SocketTimeoutException: timeout
	at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.kt:675)
	at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.kt:684)
	at okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.kt:143)
	at okhttp3.internal.http2.Http2ExchangeCodec.readResponseHeaders(Http2ExchangeCodec.kt:97)
	at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:110)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:93)
```

Unfortunately this is failing with a read timeout reading the response **before** the request has finished sending! This is because Wire + gRPC uses a duplex body.

We should not fail with read timeouts in this case.

I suspect we’ll need to fix this in OkHttp for all users of duplex calls. I don’t think we can fix it in Wire because there’s no APIs on Call or Call.Factory to manipulate read timeouts.

**Comment by swankjesse** [comment]
Just needs OkHttp 5.0.0-alpha.8 or newer. No further action on this.

**Comment by ln-12** [comment]
Hey @swankjesse, do you see any chance to use streams without waiting for OkHttp 5 to become stable (maybe a backport of the needed functionality to OkHttp 4)? We would love to use wire instead of [grpc-kotlin](https://github.com/grpc/grpc-kotlin) to have Kotlin code generated, but we definitely need streaming support and don't want to include alpha dependencies.
