### ISSUE TITLE
Exception on Windows (GitHub Actions) and protoSource pointing to an external dependency with Gradle

### ISSUE THREAD

**Issue by anuraaga** [square/wire#2188]
I currently get this exception in a build on Windows GitHub actions

```
Caused by: java.lang.IllegalArgumentException: 'other' has different root
	at org.gradle.api.internal.file.AbstractBaseDirFileResolver.resolveAsRelativePath(AbstractBaseDirFileResolver.java:34)
	at org.gradle.api.internal.file.DefaultFileOperations.relativePath(DefaultFileOperations.java:224)
	at org.gradle.api.internal.project.DefaultProject.relativePath(DefaultProject.java:993)
	at com.squareup.wire.gradle.InputLocation$Companion.get(InputLocation.kt:20)
	at com.squareup.wire.gradle.WireInput.toLocations(WireInput.kt:165)
	at com.squareup.wire.gradle.WireInput.toLocations$lambda-5(WireInput.kt:148)
	at org.gradle.api.internal.provider.DefaultProvider.calculateOwnValue(DefaultProvider.java:66)
	at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateValue(AbstractMinimalProvider.java:103)
	at org.gradle.api.internal.provider.Collectors$ElementsFromCollectionProvider.collectEntries(Collectors.java:216)
	at org.gradle.api.internal.provider.AbstractCollectionProperty$CollectingSupplier.calculateValue(AbstractCollectionProperty.java:337)
	at org.gradle.api.internal.provider.AbstractCollectionProperty.finalValue(AbstractCollectionProperty.java:189)
	at org.gradle.api.internal.provider.AbstractCollectionProperty.finalValue(AbstractCollectionProperty.java:37)
	at org.gradle.api.internal.provider.AbstractProperty.finalizeNow(AbstractProperty.java:236)
	... 75 more
```

https://github.com/open-telemetry/opentelemetry-java/runs/4848361165?check_suite_focus=true
https://scans.gradle.com/s/gcykxyqgarzqw

We reference an external dependency containing proto files like this

https://github.com/open-telemetry/opentelemetry-java/blob/6ab88fbc00bf3bf40b033d523aa9d430d08c0cfb/exporters/otlp/common/build.gradle.kts#L16

Presumably GitHub windows runner puts caches on a separate drive from the actual build. The caches include external dependency jars and cause that exception when trying to handle them.

This line does not use the "windows-aware" factory of `InputLocation`.

https://github.com/square/wire/blob/18864764e6b65ca8a83e040095e8f2a44c27a0b7/wire-library/wire-gradle-plugin/src/main/kotlin/com/squareup/wire/gradle/WireInput.kt#L165

I was looking into whether there is a quick fix but came upon a possible design issue. The task input is a list of wire's `InputLocation`

https://github.com/square/wire/blob/18864764e6b65ca8a83e040095e8f2a44c27a0b7/wire-library/wire-gradle-plugin/src/main/kotlin/com/squareup/wire/gradle/WireTask.kt#L54

I'm wondering why these aren't just `FileCollection` and pass in the `Configuration` directly which is currently mapped into `InputLocation` via `WireInput.toLocations`. I think Gradle should be able to do the smartest thing with `@InputFiles`/`@PathSensitivity` or even `@Classpath` may be appropriate for it. That would allow the wire plugin to let Gradle worry about cachability and not in wire business logic like here

https://github.com/square/wire/blob/18864764e6b65ca8a83e040095e8f2a44c27a0b7/wire-library/wire-gradle-plugin/src/main/kotlin/com/squareup/wire/gradle/InputLocation.kt#L16

Does this make sense? If so, I can try a PR - wanted to get any already known issues with that approach though as there seems to have been real effort put into abstracting the files through `InputLocation` and I'm probably missing something.

**Comment by oldergod** [comment]
Won't fix for now.
