### ISSUE TITLE
java.lang.UnsupportedOperationException: map types not supported

### ISSUE THREAD

**Issue by gigi** [square/wire#2329]
Hello! Thanx for this great lib! It saved me a lot of time.

We use it to parse .proto schemas in runtime.

However I can't understand how to parse maps properly. According to [this doc](https://github.com/square/wire/issues/279) maps deserialization is supported somehow.

For example I have proto declaration:

```proto

syntax = "proto3";

package xxx.xxx.protocol;

message State {
  map<string, int64> currencies = 1;
}

...

```

My code causing the error:

```java

  private Map<String, Object> deserializeValue(Schema schema, String messageName, byte[] data) {
    try {
      RuntimeMessageAdapter<Object, Object> adapter = getAdapter(schema, messageName);
      return (Map<String, Object>) adapter.decode(data);
    } catch (Exception exception) {
      log.error(exception.getMessage(), exception);
      return Map.of();
    }
  }

  private RuntimeMessageAdapter<Object, Object> getAdapter(Schema schema, String messageName) {
    return (RuntimeMessageAdapter<Object, Object>) schema.protoAdapter(messageName, true);
  }

```
Exception:
```
java.lang.UnsupportedOperationException: map types not supported
	at com.squareup.wire.schema.SchemaProtoAdapterFactory.get(SchemaProtoAdapterFactory.kt:59) ~[wire-schema-jvm-4.4.1.jar:na]
	at com.squareup.wire.schema.SchemaProtoAdapterFactory$SchemaFieldOrOneOfBinding.getSingleAdapter(SchemaProtoAdapterFactory.kt:226) ~[wire-schema-jvm-4.4.1.jar:na]
	at com.squareup.wire.internal.FieldOrOneOfBinding$adapter$2.invoke(FieldOrOneOfBinding.kt:64) ~[wire-runtime-jvm-4.4.1.jar:na]
	at com.squareup.wire.internal.FieldOrOneOfBinding$adapter$2.invoke(FieldOrOneOfBinding.kt:59) ~[wire-runtime-jvm-4.4.1.jar:na]
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) ~[kotlin-stdlib-1.6.10.jar:1.6.10-release-923(1.6.10)]
	at com.squareup.wire.internal.FieldOrOneOfBinding.getAdapter(FieldOrOneOfBinding.kt:59) ~[wire-runtime-jvm-4.4.1.jar:na]
	at com.squareup.wire.internal.RuntimeMessageAdapter.decode(RuntimeMessageAdapter.kt:159) ~[wire-runtime-jvm-4.4.1.jar:na]
	at com.squareup.wire.ProtoAdapter.decode(ProtoAdapter.kt:374) ~[wire-runtime-jvm-4.4.1.jar:na]
	at com.squareup.wire.ProtoAdapter.decode(ProtoAdapter.kt:372) ~[wire-runtime-jvm-4.4.1.jar:na]
...
```

So, how to deal with this exception properly? 

https://github.com/square/wire/blob/4.4.1/wire-library/wire-schema/src/commonMain/kotlin/com/squareup/wire/schema/SchemaProtoAdapterFactory.kt#L59

Thanx for help

**Comment by oldergod** [comment]
Maps are only supported when used with the `google.protobuf.Struct`. We unfortunately don't have plans to support vanilla map fields at the moment.

**Comment by oldergod** [comment]
I've created a failing test in #2513
