### ISSUE TITLE
ClassCastException thrown when processing a message with non-empty map in MessageOptions

### ISSUE THREAD

**Issue by chalup** [square/wire#2414]
Wire fails to process a `map` entries for `MessageOptions`:

```proto
syntax = "proto3";

import "google/protobuf/descriptor.proto";

package wire.issue;

message Options {
  map<string, string> config = 1;
}

extend google.protobuf.MessageOptions {
  repeated Options opt = 80000;
}

message SomeMessage {
  option (wire.issue.opt) = {
    config: [
      {
        key: "some_key",
        value: "some_value"
      }
    ]
  };

  string id = 1;
}
```

Running a `generateMainProtos` task fails with:

```
Execution failed for task ':generateMainProtos'.
> class java.lang.String cannot be cast to class com.squareup.wire.schema.ProtoMember (java.lang.String is in module java.base of loader 'bootstrap'; com.squareup.wire.schema.ProtoMember is in unnamed module of loader org.gradle.internal.classloader.VisitableURLClassLoader @27d48cdf)
```

Full stacktrace:

```
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':generateMainProtos'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:147)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:282)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:145)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:133)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:74)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:333)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:320)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:313)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:299)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:143)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:227)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:218)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:140)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
Caused by: java.lang.ClassCastException: class java.lang.String cannot be cast to class com.squareup.wire.schema.ProtoMember (java.lang.String is in module java.base of loader 'bootstrap'; com.squareup.wire.schema.ProtoMember is in unnamed module of loader org.gradle.internal.classloader.VisitableURLClassLoader @27d48cdf)
        at com.squareup.wire.schema.Options.gatherFields(Options.kt:310)
        at com.squareup.wire.schema.Options.gatherFields(Options.kt:318)
        at com.squareup.wire.schema.Options.gatherFields(Options.kt:313)
        at com.squareup.wire.schema.Options.gatherFields(Options.kt:318)
        at com.squareup.wire.schema.Options.gatherFields(Options.kt:313)
        at com.squareup.wire.schema.Options.fields(Options.kt:297)
        at com.squareup.wire.schema.Pruner.reachableObjects(Pruner.kt:245)
        at com.squareup.wire.schema.Pruner.markReachable(Pruner.kt:125)
        at com.squareup.wire.schema.Pruner.prune(Pruner.kt:38)
        at com.squareup.wire.schema.Schema.prune(Schema.kt:56)
        at com.squareup.wire.schema.WireRun.refactorSchema(WireRun.kt:310)
        at com.squareup.wire.schema.WireRun.execute(WireRun.kt:222)
        at com.squareup.wire.schema.WireRun.execute(WireRun.kt:211)
        at com.squareup.wire.schema.WireRun.execute$default(WireRun.kt:210)
        at com.squareup.wire.gradle.WireTask.generateWireFiles(WireTask.kt:164)
```

The issue can be reproduced using this project: https://github.com/chalup/wire-map-option-issue

**Comment by oldergod** [comment]
I might have time this week!
