### ISSUE TITLE
Unable to find method ''okio.FileSystem okio.Okio.asResourceFileSystem(java.lang.ClassLoader)''

### ISSUE THREAD

**Issue by vivek-meesho** [square/wire#2428]
Getting this error on using api "com.squareup.wire:wire-runtime:4.4.0" in build.gradle of my module

<img width="1271" alt="Screenshot 2023-04-06 at 4 55 51 PM" src="https://user-images.githubusercontent.com/100408301/230363424-14b393db-4952-4cab-ac23-ed77880a990f.png">

Unable to find method ''okio.FileSystem okio.Okio.asResourceFileSystem(java.lang.ClassLoader)''
'okio.FileSystem okio.Okio.asResourceFileSystem(java.lang.ClassLoader)'

Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)

Gradle version : 7.2.0 
Android studio version : Android Studio Electric Eel | 2022.1.1 Patch 2 
 
Stack Trace:
Caused by: java.lang.NoSuchMethodError: 'okio.FileSystem okio.Okio.asResourceFileSystem(java.lang.ClassLoader)'
        at com.squareup.wire.schema.CoreLoader$resourceFileSystem$2.invoke(CoreLoader.kt:34)
        at com.squareup.wire.schema.CoreLoader$resourceFileSystem$2.invoke(CoreLoader.kt:33)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.squareup.wire.schema.CoreLoader.getResourceFileSystem(CoreLoader.kt:33)
        at com.squareup.wire.schema.CoreLoader.load(CoreLoader.kt:39)
        at com.squareup.wire.schema.internal.CommonSchemaLoader.load(CommonSchemaLoader.kt:148)
        at com.squareup.wire.schema.Linker.getFileLinker$wire_schema(Linker.kt:74)
        at com.squareup.wire.schema.Linker.link(Linker.kt:87)
        at com.squareup.wire.schema.internal.CommonSchemaLoader.loadSchema(CommonSchemaLoader.kt:103)
        at com.squareup.wire.schema.SchemaLoader.loadSchema(SchemaLoader.kt:71)
        at com.squareup.wire.schema.WireRun.execute(WireRun.kt:219)
        at com.squareup.wire.schema.WireRun.execute(WireRun.kt:211)
        at com.squareup.wire.schema.WireRun.execute$default(WireRun.kt:210)
        at com.squareup.wire.gradle.WireTask.generateWireFiles(WireTask.kt:164)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:58)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:51)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:29)
        at org.gradle.api.internal.tasks.execution.TaskExecution$2.run(TaskExecution.java:239)

**Comment by oldergod** [comment]
Can you confirm the version of Okio is getting used? Should be good if it's using `3.1.x` and above

**Comment by vivek-meesho** [comment]
It's 3.0.0 for okio

**Comment by vivek-meesho** [comment]
Tried increasing it to 3.1.0 (also 3.2.0 and 3.3.0) but then getting this error: /Users/vivekgiri/.gradle/caches/modules-2/files-2.1/com.squareup.okio/okio-jvm/3.3.0/2d175add2d06a67bda111ae5455e49b42d0bb287/okio-jvm-3.3.0.jar!/META-INF/okio.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.

Changed kotlin version to 1.6.0 from 1.6.21 and gradle plugin version to 7.0.4 from 7.2.0 after seeing above error, but the issue persists

**Comment by vivek-meesho** [comment]
@oldergod can you help here

**Comment by matejdro** [comment]
Still happening with Wire 4.5.6. Adding okio `3.3.0` to the buildscript (not project) classpath resolves the issue.

**Comment by oldergod** [comment]
If this is still happening, confirm the version of Okio resolves to `3.3.0` or above.
