### ISSUE TITLE
NoSuchFieldError: Companion

### ISSUE THREAD

**Issue by sylwester-zielinski** [square/wire#2556]
Hi, I'm getting this error when trying run generateDebugProtos task. 
Do you have any idea what can be the issue?

```
Caused by: java.lang.NoSuchFieldError: Companion
	at okio.internal._PathKt.<clinit>(-Path.kt:26)
	at okio.Path$Companion.get(Path.kt:118)
	at okio.Path$Companion.get$default(Path.kt:118)
	at okio.FileSystem.<clinit>(FileSystem.kt:143)
	at com.squareup.wire.gradle.WireTask.generateWireFiles(WireTask.kt:171)
```

**Comment by oldergod** [comment]
Which Wire version is this? and could you confirm which Okio version it's resolving to?

**Comment by sylwester-zielinski** [comment]
Sorry for the late response. I noticed that wire is a dependency which is no longer required in the project so I safely removed it.

I'm closing the issue then.
