### ISSUE TITLE
serialization issue with repeated fields and [packed = true] when used in embedded messages

### ISSUE THREAD

**Issue by SkinnerAnonymous** [square/wire#541]
Hi Guys,
Never posted something on github before, so if this is the wrong place to post issues on the topic, please let me know. And before I start, let me say thank you for the wire protobuf library. It’s a great utility for android app development!

Now to the issue: The current versions of Wire seem to have problems with the serialization/deserialization of repeated fields inside embedded messages when using the [packed = true] option. When the repeated field is not set but other fields inside the embedded message are, serialization/deserialization either does not work (IOException, see below) or fails at (de-)serializing the message correctly (values assigned to wrong fields or dropping fields completely). The problems are easily recreated, so I included below three cases that I stumbled across. I tested them with 2.0.1, 2.0.2 and 2.0.3. The result is always the same. Wire versions prior to 2.0.0 seem not to have this problem/these problems. I am using wire-compiler-VERSION-jar-with-dependencies.jar to compile the proto files and the gradle dependency 'com.squareup.wire:wire-runtime:VERSION' in Android Studio.

CASE 1: - IOException thrown -

Proto File:
package com.test;
message EmbeddedMessage {
    repeated int32 inner_repeated_number = 1 [packed=true];
    optional int32 inner_number_after = 2;
}
message OuterMessage {
  optional int32 outer_number_before = 1;
  optional EmbeddedMessage embedded_message = 2;
}

Java code:
```java
try {
    EmbeddedMessage.Builder embeddedMessageBuilder = new EmbeddedMessage.Builder();
    embeddedMessageBuilder.inner_number_after(1);
    OuterMessage.Builder outerMessageBuilder = new OuterMessage.Builder();
    outerMessageBuilder
        .outer_number_before(2)
        .embedded_message(embeddedMessageBuilder.build());
    byte[] outerMessagesBytes = OuterMessage.ADAPTER.encode(outerMessageBuilder.build());
    OuterMessage outerMessagesAfterSerialisation = OuterMessage.ADAPTER.decode(outerMessagesBytes);
} catch (Exception e) {
    e.printStackTrace();
}
```

Error Message:
```java
01-18 17:22:29.999 4344-4344/com.test W/System.err: java.io.IOException: Expected to end at 8 but was 6
01-18 17:22:30.039 4344-4344/com.test W/System.err:     at com.squareup.wire.ProtoReader.endMessage(ProtoReader.java:117)
01-18 17:22:30.039 4344-4344/com.test W/System.err:     at com.test.EmbeddedMessage$ProtoAdapter_EmbeddedMessage.decode(EmbeddedMessage.java:150)
01-18 17:22:30.039 4344-4344/com.test W/System.err:     at com.test.EmbeddedMessage$ProtoAdapter_EmbeddedMessage.decode(EmbeddedMessage.java:116)
01-18 17:22:30.039 4344-4344/com.test W/System.err:     at com.test.OuterMessage$ProtoAdapter_OuterMessage.decode(OuterMessage.java:138)
01-18 17:22:30.039 4344-4344/com.test W/System.err:     at com.test.OuterMessage$ProtoAdapter_OuterMessage.decode(OuterMessage.java:112)
01-18 17:22:30.039 4344-4344/com.test W/System.err:     at com.squareup.wire.ProtoAdapter.decode(ProtoAdapter.java:176)
01-18 17:22:30.039 4344-4344/com.test W/System.err:     at com.squareup.wire.ProtoAdapter.decode(ProtoAdapter.java:164)
01-18 17:22:30.039 4344-4344/com.test W/System.err:     at com.test.MainActivity.onCreate(MainActivity.java:21)
01-18 17:22:30.044 4344-4344/com.test W/System.err:     at android.app.Activity.performCreate(Activity.java:5372)
01-18 17:22:30.044 4344-4344/com.test W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1104)
01-18 17:22:30.044 4344-4344/com.test W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2257)
01-18 17:22:30.044 4344-4344/com.test W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2349)
01-18 17:22:30.044 4344-4344/com.test W/System.err:     at android.app.ActivityThread.access$700(ActivityThread.java:159)
01-18 17:22:30.044 4344-4344/com.test W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316)
01-18 17:22:30.044 4344-4344/com.test W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
01-18 17:22:30.044 4344-4344/com.test W/System.err:     at android.os.Looper.loop(Looper.java:176)
01-18 17:22:30.049 4344-4344/com.test W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5419)
01-18 17:22:30.049 4344-4344/com.test W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
01-18 17:22:30.049 4344-4344/com.test W/System.err:     at java.lang.reflect.Method.invoke(Method.java:525)
01-18 17:22:30.049 4344-4344/com.test W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046)
01-18 17:22:30.049 4344-4344/com.test W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
01-18 17:22:30.049 4344-4344/com.test W/System.err:     at dalvik.system.NativeStart.main(Native Method)
```

CASE 2: - Incorrectly assigned value -

Proto File:
package com.test;
message EmbeddedMessage {
  optional int32 inner_number_before = 1;
  repeated int32 inner_repeated_number = 2 [packed=true];
  optional int32 inner_number_after_1 = 3;
  optional int32 inner_number_after_2 = 4;
}
message OuterMessage {
  optional int32 outer_number_before = 1;
  optional EmbeddedMessage embedded_message = 2;
  optional int32 outer_number_after = 3;
}

Java code:
```java
try {
    EmbeddedMessage.Builder embeddedMessageBuilder = new EmbeddedMessage.Builder();
    embeddedMessageBuilder
        .inner_number_before(1)
        .inner_number_after_1(2)
        .inner_number_after_2(3);
    OuterMessage.Builder outerMessageBuilder = new OuterMessage.Builder();
    outerMessageBuilder
        .outer_number_before(4)
        .embedded_message(embeddedMessageBuilder.build())
        .outer_number_after(5);
    byte[] outerMessagesBytes = OuterMessage.ADAPTER.encode(outerMessageBuilder.build());
    OuterMessage outerMessagesAfterSerialisation = OuterMessage.ADAPTER.decode(outerMessagesBytes);
    System.out.println(outerMessagesAfterSerialisation.toString());
} catch (Exception e) {
    e.printStackTrace();
}
```

Output:
```java
01-18 17:40:21.009 22666-22666/com.test I/System.out: OuterMessage{outer_number_before=4, embedded_message=EmbeddedMessage{inner_number_before=1, inner_repeated_number=[], inner_number_after_1=5, inner_number_after_2=3}}
```

CASE 3: - Dropping fields -
Proto File:
package com.test;
message EmbeddedMessage {
  optional int32 inner_number_before = 1;
  repeated int32 inner_repeated_number = 2 [packed=true];
}
message OuterMessage {
  optional int32 outer_number_before = 1;
  optional EmbeddedMessage embedded_message = 2;
  optional int32 outer_number_after = 3;
}

Java code:
```java
try {
    EmbeddedMessage.Builder embeddedMessageBuilder = new EmbeddedMessage.Builder();
    embeddedMessageBuilder
        .inner_number_before(1);
    OuterMessage.Builder outerMessageBuilder = new OuterMessage.Builder();
    outerMessageBuilder
        .outer_number_before(2)
        .embedded_message(embeddedMessageBuilder.build())
        .outer_number_after(3);
    byte[] outerMessagesBytes = OuterMessage.ADAPTER.encode(outerMessageBuilder.build());
    OuterMessage outerMessagesAfterSerialisation = OuterMessage.ADAPTER.decode(outerMessagesBytes);
    System.out.println(outerMessagesAfterSerialisation.toString());
} catch (Exception e) {
    e.printStackTrace();
}
```

Output:
```java
01-18 17:48:44.134 32082-32082/com.test I/System.out: OuterMessage{outer_number_before=2, embedded_message=EmbeddedMessage{inner_number_before=1, inner_repeated_number=[]}}
```

**Comment by swankjesse** [comment]
Wow, this is quite severe. I’ll investigate & see what’s up.

**Comment by swankjesse** [comment]
@SkinnerAnonymous I’ve embedded your sample in our test code. If you’re not comfortable with this, please let me know & I’ll write a new example from scratch.
