### ISSUE TITLE
Crash on duplicated tags

### ISSUE THREAD

**Issue by swankjesse** [square/wire#608]
We saw a problem where something like this wasn’t crashing as we would expect.
```
message Message {
  optional int64 a = 1;
  optional int64 b = 1;
}
```

**Comment by swankjesse** [comment]
It already crashes. 

```

com.squareup.wire.schema.SchemaException: multiple fields share tag 1:
  1. field (message.proto at 3:3)
  2. field_again (message.proto at 4:3)
  for message Message (message.proto at 2:1)

	at com.squareup.wire.schema.Linker.link(Linker.java:119)
	at com.squareup.wire.schema.SchemaLoader.loadFromDirectories(SchemaLoader.java:167)
	at com.squareup.wire.schema.SchemaLoader.load(SchemaLoader.java:106)
	at com.squareup.wire.schema.SchemaBuilder.build(SchemaBuilder.java:63)
	at com.squareup.wire.java.JavaGeneratorTest.generateProtoFields(JavaGeneratorTest.java:52)
```
