### ISSUE TITLE
Wire Plugin: Failed to write (no package).MyClass

### ISSUE THREAD

**Issue by heuermh** [square/wire#610]
After placing [phenopacket.proto](https://github.com/phenopackets/phenopacket-format/blob/master/schema/phenopacket.proto) in `src/main/proto` and configuring the wire-maven-plugin, I get the following error

```bash
$ mvn package
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building adam-pheno_2.10 0.19.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:3.0.0:clean (default-clean) @ adam-pheno_2.10 ---
[INFO] Deleting /Users/heuermh/working/adam-pheno/target
[INFO] 
[INFO] --- maven-enforcer-plugin:1.2:enforce (enforce-maven) @ adam-pheno_2.10 ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.2:enforce (enforce-java) @ adam-pheno_2.10 ---
[INFO] 
[INFO] --- wire-maven-plugin:2.2.0:generate-sources (default) @ adam-pheno_2.10 ---
[INFO] Loaded 2 proto files in 400.4 ms
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.212 s
[INFO] Finished at: 2016-07-13T15:48:50-05:00
[INFO] Final Memory: 17M/132M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.squareup.wire:wire-maven-plugin:2.2.0:generate-sources
 (default) on project adam-pheno_2.10: Wire Plugin: Failure compiling proto sources. Failed to
write .PhenoPacket to /Users/heuermh/working/adam-pheno/target/generated-sources/wire:
/Users/heuermh/working/adam-pheno/target/generated-sources/wire/PhenoPacket.java -> [Help 1]

$ mvn -e package
...
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Wire Plugin: Failure compiling proto sources.
	at com.squareup.wire.mojo.WireGenerateSourcesMojo.execute(WireGenerateSourcesMojo.java:103)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: java.io.IOException: Failed to write .PhenoPacket to /Users/heuermh/working/adam-pheno/target/generated-sources/wire
	at com.squareup.wire.mojo.WireGenerateSourcesMojo.writeJavaFile(WireGenerateSourcesMojo.java:179)
	at com.squareup.wire.mojo.WireGenerateSourcesMojo.execute(WireGenerateSourcesMojo.java:98)
	... 22 more
Caused by: java.nio.file.NoSuchFileException: /Users/heuermh/working/adam-pheno/target/generated-sources/wire/PhenoPacket.java
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434)
	at java.nio.file.Files.newOutputStream(Files.java:216)
	at com.squareup.javapoet.JavaFile.writeTo(JavaFile.java:97)
	at com.squareup.javapoet.JavaFile.writeTo(JavaFile.java:104)
	at com.squareup.wire.mojo.WireGenerateSourcesMojo.writeJavaFile(WireGenerateSourcesMojo.java:177)
	... 23 more
```

The error is reported [here](https://github.com/square/wire/blob/master/wire-maven-plugin/src/main/java/com/squareup/wire/mojo/WireGenerateSourcesMojo.java#L179), where it looks like `javaFile.packageName` is not defined.

Is the proto schema missing or incorrectly defining package names?  Or am I missing configuration to the wire-maven-plugin?  Or do I need to break up the proto schema file into separate package directories under `src/main/proto`?

In any case, the error message could be more helpful.

Full source is at https://github.com/heuermh/adam-pheno

**Comment by heuermh** [comment]
Adding either a `package` or `option java_package` statement fixed the problem.  Feel free to reopen this issue if you feel the error message needs improvement.

The code has since been moved to https://github.com/heuermh/phenopacket-protobuf
