### ISSUE TITLE
Confict with Protobuf Official Java SDK

### ISSUE THREAD

**Issue by VolodymyrCj** [square/wire#679]
My android app has both [official java sdk](https://github.com/google/protobuf) and wire, when I open it in the mobile after proguard, the following error occurs:
```java
java.lang.NoSuchMethodError: No super method buildUnknownFields()Lokio/ByteString; in class Lcom/squareup/wire/Message$Builder; or its super classes (declaration of 'com.squareup.wire.Message$Builder')
	at com.dji.service.areacode.wire.DJIACCityModel$a.a(Unknown Source)
	at com.dji.service.areacode.wire.DJIACCityModel$b.a(Unknown Source)
	at com.dji.service.areacode.wire.DJIACCityModel$b.decode(Unknown Source)
	at com.dji.service.areacode.wire.DJIACCityListModel$b.a(Unknown Source)
	at com.dji.service.areacode.wire.DJIACCityListModel$b.decode(Unknown Source)
	at com.squareup.wire.ProtoAdapter.decode(Unknown Source)
	at com.squareup.wire.ProtoAdapter.decode(Unknown Source)
	at com.dji.service.areacode.d.a(Unknown Source)
	at com.dji.service.areacode.d.a(Unknown Source)
	at com.dji.service.areacode.d.a(Unknown Source)
	at com.dji.service.areacode.DJIAreaCodeManger.a(Unknown Source)
	at com.dji.service.areacode.DJIAreaCodeManger.a(Unknown Source)
	at com.dji.service.areacode.DJIAreaCodeManger$e$1.handleMessage(Unknown Source)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:163)
	at android.os.HandlerThread.run(HandlerThread.java:61)
```

so how can I fix it?
Thanks!

**Comment by JakeWharton** [comment]
Does it work without ProGuard?

**Comment by VolodymyrCj** [comment]
@JakeWharton it works fine without Proguard

**Comment by JakeWharton** [comment]
Then the problem is with your ProGuard configuration into which we have no
insight. You shouldn't need any rules for Wire unless you're enabling
optimization.

**Comment by VolodymyrCj** [comment]
@JakeWharton I lack the proguard rule of that dependency, it solved finally, thanks!
