### ISSUE TITLE
Map named with keyword causes compiler to crash

### ISSUE THREAD

**Issue by swankjesse** [square/wire#799]
Looks like we aren’t using NameAllocator where we should.

```
Caused by: java.lang.IllegalArgumentException: not a valid name: protected
        at com.squareup.javapoet.Util.checkArgument(Util.java:64)
        at com.squareup.javapoet.FieldSpec.builder(FieldSpec.java:91)
        at com.squareup.wire.java.JavaGenerator.messageAdapter(JavaGenerator.java:877)
        at com.squareup.wire.java.JavaGenerator.generateMessage(JavaGenerator.java:622)
        at com.squareup.wire.java.JavaGenerator.generateType(JavaGenerator.java:389)
        at com.squareup.wire.JavaFileWriter.call(JavaFileWriter.java:55)
        at com.squareup.wire.JavaFileWriter.call(JavaFileWriter.java:30)
```

**Comment by Catherinelhl** [comment]
Same error,annd want somebody keep mind.thank y
