### ISSUE TITLE
WireCompiler throws Exception when message extensions have fields with the same names

### ISSUE THREAD

**Issue by cjustice** [square/wire#857]
The following `example.proto`:

```
syntax = "proto2";

message Base {
}

message ExtensionOne {
	extend Base {
		optional string value = 100;
	}
}

message ExtensionTwo {
	extend Base {
		optional string value = 200;
	}
}
```

Fails when running WireCompiler:

```
~/Development/scratch java -jar wire-compiler-2.3.0-RC1-jar-with-dependencies.jar --proto_path="." --java_out=out example.proto 
Exception in thread "main" com.squareup.wire.schema.SchemaException: multiple fields share name value:
  1. value (./example.proto at 8:3)
  2. value (./example.proto at 14:3)
  for message Base (./example.proto at 3:1)
	at com.squareup.wire.schema.Linker.link(Linker.java:119)
	at com.squareup.wire.schema.SchemaLoader.loadFromDirectories(SchemaLoader.java:167)
	at com.squareup.wire.schema.SchemaLoader.load(SchemaLoader.java:106)
	at com.squareup.wire.WireCompiler.compile(WireCompiler.java:217)
	at com.squareup.wire.WireCompiler.main(WireCompiler.java:132)
```

This seems to be because the two extensions of `Base` have fields with the same name, `value`. This isn't part of the language spec, as far as I can tell, and is specific to WireCompiler. 

*Expected Outcome*: Proto compilation succeeds. These should be valid messages (they are compiled correctly by other protobuf compilers).

**Comment by oldergod** [comment]
Wire supports it if the extensions are defined in different packages.

Now, I just tried with protoc `3.11.4` for the following proto schema
```
syntax = "proto2";

message Base {
  extensions 100, 200;
}

extend Base {
  optional string value = 100;
}

extend Base {
  optional string value = 200;
}
```
 and got an error
`> protoc: stdout: . stderr: example.proto:12:19: "value" is already defined.`
