### ISSUE TITLE
GrpcTest#cancelChannel is flaky

### ISSUE THREAD

**Issue by jrodbx** [square/wire#876]
```
com.squareup.wire.GrpcTest > cancelChannel FAILED
    java.lang.AssertionError: script had stuff left over: []
        at com.squareup.wire.MockRouteGuideService.awaitSuccess(MockRouteGuideService.kt:65)
        at com.squareup.wire.MockRouteGuideService$awaitSuccess$1.invokeSuspend(MockRouteGuideService.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
        at kotlinx.coroutines.ResumeModeKt.resumeUninterceptedWithExceptionMode(ResumeMode.kt:56)
        at kotlinx.coroutines.TimeoutCoroutine.onCompletionInternal$kotlinx_coroutines_core(Timeout.kt:96)
        at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:305)
        at kotlinx.coroutines.JobSupport.tryFinalizeFinishingState(JobSupport.kt:230)
        at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:799)
        at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:742)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:117)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:45)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:285)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.kt:116)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:76)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:53)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:35)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at com.squareup.wire.GrpcTest.cancelChannel(GrpcTest.kt:266)
```

**Comment by oldergod** [comment]
Ignored in #877 for now

**Comment by oldergod** [comment]
This test case doesn't exist anymore so closing for now, let me know if this happens again.
