### ISSUE TITLE
service.type().enclosingTypeOrPackage() must not be null

### ISSUE THREAD

**Issue by edenman** [square/wire#981]
I'm starting to use Wire in a new project.

``` 
java -jar ../wire-compiler-3.0.0-alpha01-jar-with-dependencies.jar --proto_path=server/src/main/proto/ --kotlin_out=android/src/main/kotlin/
```

...Writing a bunch of classes...
```
Exception in thread "main" java.io.IOException: java.lang.IllegalStateException: service.type().enclosingTypeOrPackage() must not be null
	at com.squareup.wire.WireCompiler.compile(WireCompiler.kt:178)
	at com.squareup.wire.WireCompiler$Companion.main(WireCompiler.kt:208)
	at com.squareup.wire.WireCompiler.main(WireCompiler.kt)
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: service.type().enclosingTypeOrPackage() must not be null
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.squareup.wire.WireCompiler.compile(WireCompiler.kt:175)
	... 2 more
Caused by: java.lang.IllegalStateException: service.type().enclosingTypeOrPackage() must not be null
	at com.squareup.wire.KotlinFileWriter.generateFileForService(KotlinFileWriter.kt:77)
	at com.squareup.wire.KotlinFileWriter.call(KotlinFileWriter.kt:44)
	at com.squareup.wire.KotlinFileWriter.call(KotlinFileWriter.kt:29)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Is there something I need to do to specify the enclosing type?  My proto file looks roughly like this:

```
syntax = "proto3";

option java_package = "com.coffeetrainlabs.myapp.api.generated";

service MyAppService {
    rpc GetFoos(GetFoosRequest) returns (GetFoosResponse);
}

message GetFoosRequest {

}

message GetFoosResponse {
    repeated Foo items = 1;
}

message Foo {
    string Name = 1;
}
```

**Comment by swankjesse** [comment]
That's our bug. In the interim, add a regular proto package declaration?

**Comment by swankjesse** [comment]
Oh and BTW, Wire doesn’t yet implement proto3.
